[build-system]
requires = ["setuptools >= 61.0",]
build-backend = "setuptools.build_meta"

[project]
name = "first-llm-classifier"
description = "Learn how journalists use large-language models to organize and analyze massive datasets"
version = "1.0.0"
requires-python = "==3.13.*"
dependencies = [
    # Docs stuff
    "sphinx",
    "sphinx-autobuild",
    "myst-parser",
    "sphinx-palewire-theme",
    # Tutorial depeendencies
    "bln",
    "pandas",
    "altair",
    "jupyterlab",
    "geopandas",
    "huggingface-hub",
    # Dev stuff
    "pre-commit",
    "rich>=14.3.3",
]

[tool.setuptools]
packages = ["docs",]

[tool.ruff]
exclude = ["_notebooks"]
